# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: docker.io/postgres:17.2
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: test_pass
      POSTGRES_USER: bus_bot_admin
      POSTGRES_DB: bus_bot
    ports:
      - 5432:5432

  adminer:
    image: docker.io/adminer
    restart: always
    ports:
      - 8080:8080
